name: "acrobot_dp"
simulation_step: 0.002
state_space:
  lower_bound:
    - 0
    - 0
    - -30
    - -30
  upper_bound:
    - 6.2831853072
    - 6.2831853072
    - 30
    - 30
  values:
    - 0
    - 0
    - 0
    - 0
control_space:
  lower_bound:
    - -6
  upper_bound:
    - 6
  values:
    - 0
parameter_space:
  lower_bound:
    []
  upper_bound:
    []
  values:
    []
vis_body: "ball"