name: "acrobot_pid"
simulation_step: 0.002
state_space:
  lower_bound:
    - -12.5663706144
    - -12.5663706144
    - -25
    - -25
    - -6
    - -3000
  upper_bound:
    - 12.5663706144
    - 12.5663706144
    - 25
    - 25
    - 6
    - 3000
  values:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
control_space:
  lower_bound:
    - -6
  upper_bound:
    - 6
  values:
    - 0
parameter_space:
  lower_bound:
    []
  upper_bound:
    []
  values:
    [1]
vis_body: "ball"
lqr:
  K: [-218.67, -91.0951, -46.2969, -21.0909, 0, 0]