state_space:
  lower_bound:
    - -9.4199999999999999
    - -9.4199999999999999
    - -30
    - -30
  upper_bound:
    - 9.4199999999999999
    - 9.4199999999999999
    - 30
    - 30
  values:
    - 0
    - 0
    - 0
    - 0
control_space:
  lower_bound:
    - -6
  upper_bound:
    - 6
  values:
    - 0
parameter_space:
  lower_bound:
    []
  upper_bound:
    []
  values:
    []