simulation_step: 0.002
random_seed: 112392
visualize: false 

bnb: true
use_replanning: false
control_steps:
  min: 50
  max: 500
blossom_number: 1
cost_multiplier: 1
w_c: 1
w_x: 1
min_cost: 0.1
checker:
  type: time
  value: 2       # secs
  # repeats: 10     
  repeats: 30 